### ISSUE TITLE
port 25

### ISSUE THREAD

**Issue by guillim** [eliashussary/mail-confirm#1]
I have been trying to install your package. I am facing one problem... exactly the problem you mentioned in the doc, with port 25 not accessible I think. So when I launch

```
const check = async (email) => {  
  try{
      const emailResponse = new MailConfirm({
          emailAddress: email,
          timeout: 5000,
          mailFrom: 'from@email.com',
          invalidMailboxKeywords: ['noreply', 'noemail']
      });
      const result = await emailResponse.check()
      return result
  }catch(err){   throw new Error(err)    }
}

 check('to@email.com');

```
Here is the log error:
`Error: Mailbox check failed.
`

However, I have been trying different things to fix this, but no success yet. I would love your word on how you manage it !!!

My config: using a mac IOS 10.12
I have been trying to `sudo launchctl start org.postfix.master` to enable port 25, so now i see 25 open: 
```Nmap scan report for localhost (127.0.0.1)
Host is up (0.000098s latency).
Other addresses for localhost (not scanned): ::1
Not shown: 1989 closed ports
PORT      STATE         SERVICE
25/tcp    open          smtp
587/tcp   open          submission
631/tcp   open          ipp
3000/tcp  open          ppp
3001/tcp  open          nessus
49152/tcp open          unknown
49153/tcp open          unknown
123/udp   open          ntp
137/udp   open|filtered netbios-ns
138/udp   open|filtered netbios-dgm
5353/udp  open|filtered zeroconf`
```
But still the issue persits.

I noticed that the simple `telnet example.com 25` is hanging without answer, so it is definitly 
related to port 25. I also tried to set up s server on digitalocean to try on ubuntu servers, but same thing, `telnet example.com 25` is hanging. 

I know it is not an issue related to your package, but I won't be the only one having this problem I suppose. 
So @eliashussary : any ideas on how to make port 25 available on Mac or ubuntu in order to get your package to work ?
Any possibilities to make this package work on different port ?

thanks

**Comment by eliashussary** [comment]
Hi @guillim ,

You need to cut a ticket with DO. Unfortunately as an end user of their service you're not provided access to enable this port.

This should resolve it for you.

Wish i could be of more assistance.

Elias

**Comment by guillim** [comment]
Tks for your answer.
